blank_issues_enabled: false
contact_links:
    - name: Support Questions & Other
      url: https://stackoverflow.com/questions/ask?tags=jquery-validate
      about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
    - name: Documentation issue
      url: https://github.com/jquery-validation/validation-content
      about: For documentation issues, open a pull request at the jquery-validation/validation-content repository
