name: ci

on:
    push:
    pull_request:

jobs:
    linux_tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Run tests
              run: npm install
