# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
    schedule:
        - cron: '10 05 * * *'

jobs:
    stale:

        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write

        steps:
            - uses: actions/stale@v5
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: >
                      This issue/proposal has been automatically marked as idle and stale because it hasn't
                      had any recent activity. It will be automatically closed if no further activity
                      occurs. If you think this is wrong, or the problem still persists, just pop
                      a reply in the comments and one of the maintainers will (try!) to follow up.

                      Thank you for contributing :)
                  stale-pr-message: >
                      This issue/proposal has been automatically marked as idle and stale because it hasn't
                      had any recent activity. It will be automatically closed if no further activity
                      occurs. If you think this is wrong, or the problem still persists, just pop
                      a reply in the comments and one of the maintainers will (try!) to follow up.

                      Thank you for contributing :)
                  stale-issue-label: 'stale'
                  stale-pr-label: 'stale'
                  exempt-all-milestones: true
                  exempt-issue-labels: 'bug, help wanted'
                  exempt-pr-labels: 'MERGE ME, NEEDS REVIEW'
